apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: noobaa-db
subjects:
  - kind: ServiceAccount
    name: noobaa-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: noobaa-db
