name: KMS Test - DEV Vault, Token Auth

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

jobs:
  run-kms-dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo PATH=$PATH:$HOME/go/bin                                          >> $GITHUB_ENV
          echo OPERATOR_IMAGE=localhost:5000/noobaa/noobaa-operator:integration >> $GITHUB_ENV

      - name: Deploy Dependencies
        run: |
          bash .travis/install-5nodes-kind-cluster.sh
          bash .travis/install-dev-vault.sh
          go get -v github.com/onsi/ginkgo/ginkgo
          ginkgo version

      - name: Build NooBaa
        run: |
          make cli
          make image
          docker tag noobaa/noobaa-operator:$(go run cmd/version/main.go) $OPERATOR_IMAGE
          docker push $OPERATOR_IMAGE

      - name: Install NooBaa & Vault
        run: |
          bash  .travis/install-dev-kms-noobaa.sh

      - name: Run KMS DEV test
        run: make test-kms-dev
