name: KMS Test - TLS Vault, Token Auth
on: [push, pull_request, workflow_dispatch]

jobs:
  run-kms-tls-token-test:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Set environment variables
        run: |
          echo PATH=$PATH:$HOME/go/bin                                          >> $GITHUB_ENV
          echo OPERATOR_IMAGE=localhost:5000/noobaa/noobaa-operator:integration >> $GITHUB_ENV
          echo KUBERNETES_AUTH=false                                            >> $GITHUB_ENV

      - name: Build NooBaa
        run: |
          make cli
          make image
          docker tag noobaa/noobaa-operator:$(go run cmd/version/main.go) $OPERATOR_IMAGE

      - name: Deploy Dependencies
        run: |
          set -x
          bash .travis/install-5nodes-kind-cluster.sh
          docker push $OPERATOR_IMAGE
          bash .travis/install-tls-kms-noobaa.sh
          go get -v github.com/onsi/ginkgo/v2
          go install -mod=mod -v github.com/onsi/ginkgo/ginkgo 
          ginkgo version

      - name: Run KMS TLS Token test
        run: make test-kms-tls-token
