name: Run Operator Unit Tests

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"
  KUBERNETES_VERSION: "v1.17.3"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Deploy Dependencies
        id: deploy
        run: |
          bash .travis/install-tools.sh
          bash .travis/install-python.sh
          sudo bash .travis/install-minikube.sh

      - name: Run Generate API
        id: run-gen-api
        run: make gen-api-fail-if-dirty --always-make || exit 1

      - name: Run Build
        id: run-build
        run: make build || exit 1

      - name: Run Test
        id: run-test
        run: make test || exit 1

      - name: Run Test OLM
        id: run-test-olm
        run: sudo make test-olm || exit 1

  run-cli-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Deploy Dependencies
        id: deploy
        run: |
          bash .travis/install-tools.sh
          bash .travis/install-python.sh
          sudo bash .travis/install-minikube.sh

      - name: Run Build CLI
        id: run-build-cli
        run: make cli || exit 1

      - name: Run Build Image
        id: run-build-image
        run: make image || exit 1

      - name: Run Test CLI
        id: run-test-cli
        run: sudo make test-cli-flow || exit 1

  run-core-config-map-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Deploy Dependencies
        id: deploy
        run: |
          bash .travis/install-tools.sh
          bash .travis/install-python.sh
          sudo bash .travis/install-minikube.sh

      - name: Run Build CLI
        id: run-build-cli
        run: make cli || exit 1

      - name: Run Build Image
        id: run-build-image
        run: make image || exit 1

      - name: Run Test Core config map
        id: run-test-core-config-map-flow
        run: sudo make test-core-config-map-flow || exit 1
